name: 🐛 Bug Report
description: Report a bug or issue with the development workflow
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: ["franorzabal"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
        **Please search existing issues before creating a new one.**

  - type: input
    id: linear-issue
    attributes:
      label: Linear Issue
      description: If this relates to a Linear issue, please provide the ID (e.g., FRA-43)
      placeholder: "FRA-XXX"
    validations:
      required: false

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please complete the following information
      value: |
        - OS: [e.g. macOS, Ubuntu, Windows]
        - Shell: [e.g. bash, zsh, fish]
        - Python Version: [e.g. 3.11]
        - Git Version: [e.g. 2.40.0]
        - GitHub CLI Version: [e.g. 2.30.0]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: If applicable, add error logs or console output
      render: shell
      placeholder: Paste error logs here...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Screenshots, configuration files, etc.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues for similar problems
          required: true
        - label: I have provided all the requested information
          required: true
        - label: I have tested this on the latest version
          required: true